const topicOptions = [
    "JavaScript",
    "React",
    "Node.js",
    "MongoDB",
    "Python",
    "Machine Learning",
    "Data Structures",
    "Operating Systems",
    "Computer Networks",
    "DBMS",
];

/* -------- TOPIC → SUBTOPIC MAPPING -------- */
const topicSubtopicsMap: Record<string, string[]> = {
    JavaScript: [
        "Variables",
        "Closures",
        "Promises",
        "Async / Await",
        "Event Loop",
        "ES6+",
        "Arrays",
        "Objects",
    ],
    React: [
        "JSX",
        "Components",
        "Props",
        "State",
        "Hooks",
        "Context API",
        "React Router",
        "Performance Optimization",
    ],
    "Node.js": [
        "Event Loop",
        "Express",
        "Middleware",
        "REST APIs",
        "Authentication",
        "File System",
        "Streams",
    ],
    MongoDB: [
        "CRUD Operations",
        "Aggregation Pipeline",
        "Indexes",
        "Schema Design",
        "Mongoose",
        "Transactions",
    ],
    Python: [
        "Syntax Basics",
        "Functions",
        "OOP",
        "Virtual Environments",
        "Libraries",
        "File Handling",
    ],
    "Machine Learning": [
        "Supervised Learning",
        "Unsupervised Learning",
        "Regression",
        "Classification",
        "Neural Networks",
        "Model Evaluation",
    ],
    "Data Structures": [
        "Arrays",
        "Linked Lists",
        "Stacks",
        "Queues",
        "Trees",
        "Graphs",
        "Hash Tables",
    ],
    "Operating Systems": [
        "Processes",
        "Threads",
        "Scheduling",
        "Deadlocks",
        "Memory Management",
        "File Systems",
    ],
    "Computer Networks": [
        "OSI Model",
        "TCP/IP",
        "HTTP/HTTPS",
        "DNS",
        "Routing",
        "Network Security",
    ],
    DBMS: [
        "Normalization",
        "Indexes",
        "Joins",
        "Transactions",
        "ACID Properties",
        "Query Optimization",
    ],
};

export { topicSubtopicsMap, topicOptions }